"use client";

import { createContext, useContext, useState, ReactNode } from "react";

type Language = "en" | "vi";

const translations = {
  en: {
    // Layout / Sidebar
    appName: "TaskCommit",
    appTagline: "Behavioral Learning",
    navDashboard: "Dashboard",
    navNewAssignment: "New Assignment",
    navRoadmap: "Roadmap",
    navSocial: "Social",
    navPoints: "Points",
    navStatistics: "Statistics",
    sidebarTotalPoints: "Total Points",
    sidebarKeepEarning: "Keep earning! 🔥",

    // Header
    headerProfile: "Profile",
    langEN: "EN",
    langVI: "VI",

    // Home / Dashboard
    dashboardTitle: "Dashboard Overview",
    dashboardSubtitle: "Track your progress and manage assignments",
    totalPoints: "Total Points",
    availableBalance: "Available balance",
    atRisk: "At Risk",
    activeDeposits: "Active deposits",
    lostForever: "Lost Forever",
    missedDeadlines: "Missed deadlines",
    completedToday: "Completed Today",
    tasksFinished: "Tasks finished",
    pointsAtRiskAlert: "points at risk!",
    completeTasksAlert: "Complete tasks before deadlines to reclaim your deposited points",
    activeTasks: "Active Tasks",
    newAssignment: "+ New Assignment",
    noTasksYet: "No tasks yet. Create your first assignment!",
    createAssignment: "+ Create Assignment",
    tableTask: "Task",
    tableSubject: "Subject",
    tableDeadline: "Deadline",
    tablePointsAtRisk: "Points at Risk",
    tableStatus: "Status",
    thisWeek: "This Week",
    tasksCompleted: "Tasks Completed",
    pointsReclaimed: "Points Reclaimed",
    currentStreak: "Current Streak",
    days: "days",
    nextDeadline: "Next Deadline",
    noUpcomingDeadlines: "No upcoming deadlines",
    atStake: "At stake:",
    quickAction: "Quick Action",
    viewFullRoadmap: "View Full Roadmap",
    seeAllMicro: "See all micro-deadlines →",
    overdue: "OVERDUE",

    // Create Assignment
    createTitle: "Create New Assignment",
    createSubtitle: "Auto-generate a behavioral roadmap with AI",
    subjectCourse: "Subject / Course",
    subjectPlaceholder: "e.g., Software Engineering",
    finalDeadline: "Final Deadline",
    datePickerPlaceholder: "Select a date",
    assignmentDescription: "Assignment Description",
    descriptionPlaceholder: "e.g., Final research paper on cloud architecture",
    difficultyLevel: "Difficulty Level",
    diffEasy: "easy",
    diffMedium: "medium",
    diffHard: "hard",
    tasks: "tasks",
    progressivePointSystem: "Progressive Point System",
    progressiveDesc: "Points increase over time: early tasks = lower stakes, final tasks = maximum pressure",
    aiPowered: "AI-Powered Roadmap Generator",
    aiDesc: "Our system analyzes your assignment and automatically creates time-distributed micro-deadlines with behavioral psychology-based point deposits.",
    generateRoadmap: "Generate Roadmap",
    generatingRoadmap: "Generating AI Roadmap...",
    howItWorks: "📊 How It Works",
    step1: "AI breaks your assignment into sequential milestones",
    step2: "Each milestone gets an auto-scheduled deadline",
    step3: "Points increase progressively (higher pressure = higher stakes)",
    step4: "Complete tasks to reclaim points, miss = permanent loss",
    lossAversion: "💡 Loss Aversion",
    lossAversionDesc: "Research shows people are 2x more motivated to avoid losses than to achieve gains. Your deposited points create real commitment.",

    // Roadmap View
    allRoadmaps: "All Roadmaps",
    allRoadmapsSubtitle: "View and manage all your assignment timelines",
    deleteRoadmap: "Delete roadmap",
    deleteRoadmapTitle: "Delete this roadmap?",
    deleteRoadmapDesc: "This action cannot be undone. The roadmap and all its data will be removed.",
    deleteRoadmapRefund: "Points to refund (unfinished tasks):",
    deleteRoadmapLost: "Points permanently lost (missed deadlines):",
    deleteRoadmapNoRefund: "No points to refund.",
    deleteRoadmapConfirm: "Delete roadmap",
    deleting: "Deleting...",
    cancel: "Cancel",
    noAssignments: "No assignments yet",
    createFirstAssignment: "Create Your First Assignment",
    progress: "Progress",
    tasksDone: "Done",
    points: "Points",
    backToDashboard: "Back to Dashboard",
    due: "Due",
    overallProgress: "Overall Progress",
    tasksComplete: "Tasks Complete",
    remaining: "remaining",
    totalValue: "Total Value",
    totalPoints2: "Total points",
    pointDistStrategy: "📊 Point Distribution Strategy",
    pointDistDesc: "Notice how point values increase as deadlines approach - creating progressively higher behavioral pressure!",
    pointsCurrentlyAtRisk: "Points Currently at Risk",
    completeActiveAlert: "Complete active tasks before their deadlines to reclaim your deposited points. Missed deadlines = permanent loss!",
    assignmentTimeline: "Assignment Timeline",
    milestones: "Milestones",
    assignmentNotFound: "Assignment not found",
    createNewAssignment: "Create New Assignment",

    // Task Detail
    taskComplete: "Task Complete!",
    pointsReclaimedMsg: "Points reclaimed!",
    back: "← Back",
    deadline: "Deadline",
    pointsAtRiskLabel: "points at risk",
    completeTaskNote: "Complete this task before the deadline to reclaim all",
    description: "Description",
    taskChecklist: "Task Checklist",
    done: "done",
    warningPointLoss: "Warning: Point Loss",
    warningDesc1: "If you miss this deadline,",
    warningDesc2: "points will be permanently lost and cannot be recovered.",
    completeTaskBtn: "Complete Task & Reclaim",
    pointsSuffix: "Points",

    // Deposit Points
    pointVault: "Point Vault",
    manageDeposits: "Manage your behavioral deposits",
    totalBalance: "Total Balance",
    availablePoints: "Available Points",
    deposited: "Deposited",
    reclaimed: "Reclaimed",
    lost: "Lost Forever",
    addPoints: "Add Points",
    depositAmount: "Deposit Amount",
    depositBtn: "Deposit",
    depositNote: "💡 Deposited points will be allocated to your next assignment's micro-tasks",
    recentActivity: "Recent Activity",
    lossAversionPsych: "Loss Aversion Psychology",
    lossAversionPsychDesc: "Research shows people are 2x more motivated to avoid losses than gain rewards. Your deposited points create real commitment!",
    conversionRate: "100 ₫ = 1 point. Pay via SePay (bank transfer QR).",
    selectPackage: "Select a package",
    payWithSePay: "Pay with SePay",
    paymentProcessing: "Redirecting to SePay...",
    paymentSuccess: "Payment successful!",
    paymentError: "Payment failed",
    paymentErrorDesc: "Payment was cancelled or failed. No points were added.",
    paymentVerifying: "Verifying payment...",
    paymentPendingTitle: "Payment processing",
    paymentPendingDesc: "Your payment is being confirmed. Points will appear shortly after SePay notifies us.",
    backToWallet: "Back to Point Vault",
    sepayNotConfigured: "SePay is not configured. Add SEPAY_MERCHANT_ID and SEPAY_SECRET_KEY to .env",
    topupLabel: "Top-up via SePay",
    noTransactions: "No transactions yet",
    loading: "Loading...",

    // Social
    socialTitle: "Social Progress",
    socialSubtitle: "Compete with friends",
    yourRank: "Your Rank",
    of: "of",
    dayStreak: "Day Streak 🔥",
    completed: "Completed",
    shareProg: "Share My Progress",
    leaderboard: "Leaderboard",
    friendActivity: "Friend Activity",
    views: "views",
    reactions: "reactions",
    peerPressure: "Peer Pressure Works!",
    peerPressureDesc: "Studies show accountability partners increase success rates by 65%. Keep your friends updated!",

    // Risk Dashboard
    riskTitle: "Risk Dashboard",
    riskSubtitle: "Track losses and upcoming risks",
    totalLost: "Total Points Lost",
    forever: "forever",
    currentAtRisk: "Currently At Risk",
    missedDeadlinesStat: "Missed Deadlines",
    avgLoss: "Avg Loss / Miss",
    upcomingRisks: "Upcoming Risks",
    noUpcomingRisks: "No upcoming risks! 🎉",
    risk: "risk",
    riskTrend: "Risk Trend",
    lossHistory: "Loss History",
    lossAversionAction: "Loss Aversion in Action",
    lossAversionActionDesc: "Every point lost is gone forever. This emotional \"sting\" is designed to motivate consistent completion of micro-deadlines.",
    lost2: "Lost:",
    riskLabel: "Risk:",
    hoursLeft: "h left",
    daysLeft: "d",

    // RoadmapTimeline
    timelineActive: "active",
    timelineUpcoming: "upcoming",
    timelineLocked: "locked",
    timelineCompleted: "completed",
    completeTaskTimeline: "Complete Task",

    // PointDistributionPreview
    pointDistTitle: "Point Distribution Preview",
    pointDistEarlyLabel: "Early Task",
    pointDistFinalLabel: "Final Task",
    pointDistNote: "Final tasks carry",
    pointDistNote2: "more points than early tasks — maximum pressure when it counts!",
    pointDistPsych: "📈 Behavioral Design: Stakes escalate progressively to mirror real deadline pressure.",

    // New MVP strings
    lectureUpload: "Lecture Material (PDF)",
    lectureUploadHint: "Click to add lecture PDFs (multiple allowed)",
    lectureUploadSub: "Upload all course materials — no file limit. AI analyzes every document.",
    lectureFilesCount: "files",
    lectureRequired: "Please upload a lecture PDF",
    insufficientBalance: "Insufficient points in wallet",
    timelineForfeited: "forfeited",
    uploadNotes: "Step 1: Upload Study Notes",
    uploadNotesDesc: "Upload at least 1 file with notes from what you learned",
    uploadNotesBtn: "Choose files",
    noteRequired: "Upload at least one note file first",
    quizTitle: "Step 2: Knowledge Quiz (10 questions)",
    quizDesc: "Answer at least 7/10 correctly to complete this milestone",
    startQuiz: "Generate & Start Quiz",
    generatingQuiz: "Generating quiz with AI...",
    answerAllQuestions: "Please answer all 10 questions",
    depositOnCreate: "Points are deposited when creating a new assignment",
    uploading: "Uploading...",
    regenerateQuiz: "Regenerate quiz",
    quizHistory: "Quiz History",
    answersSaved: "Answers",
  },
  vi: {
    // Layout / Sidebar
    appName: "TaskCommit",
    appTagline: "Học Tập Hành Vi",
    navDashboard: "Bảng Điều Khiển",
    navNewAssignment: "Bài Tập Mới",
    navRoadmap: "Lộ Trình",
    navSocial: "Xã Hội",
    navPoints: "Điểm",
    navStatistics: "Thống Kê",
    sidebarTotalPoints: "Tổng Điểm",
    sidebarKeepEarning: "Tiếp tục kiếm điểm! 🔥",

    // Header
    headerProfile: "Hồ Sơ",
    langEN: "EN",
    langVI: "VI",

    // Home / Dashboard
    dashboardTitle: "Tổng Quan Bảng Điều Khiển",
    dashboardSubtitle: "Theo dõi tiến độ và quản lý bài tập",
    totalPoints: "Tổng Điểm",
    availableBalance: "Số dư khả dụng",
    atRisk: "Đang Rủi Ro",
    activeDeposits: "Tiền gửi đang hoạt động",
    lostForever: "Mất Vĩnh Viễn",
    missedDeadlines: "Hạn chót bỏ lỡ",
    completedToday: "Hoàn Thành Hôm Nay",
    tasksFinished: "Nhiệm vụ đã xong",
    pointsAtRiskAlert: "điểm đang rủi ro!",
    completeTasksAlert: "Hoàn thành nhiệm vụ trước hạn chót để thu hồi điểm đã gửi",
    activeTasks: "Nhiệm Vụ Đang Hoạt Động",
    newAssignment: "+ Bài Tập Mới",
    noTasksYet: "Chưa có nhiệm vụ. Tạo bài tập đầu tiên!",
    createAssignment: "+ Tạo Bài Tập",
    tableTask: "Nhiệm Vụ",
    tableSubject: "Môn Học",
    tableDeadline: "Hạn Chót",
    tablePointsAtRisk: "Điểm Rủi Ro",
    tableStatus: "Trạng Thái",
    thisWeek: "Tuần Này",
    tasksCompleted: "Nhiệm Vụ Hoàn Thành",
    pointsReclaimed: "Điểm Thu Hồi",
    currentStreak: "Chuỗi Hiện Tại",
    days: "ngày",
    nextDeadline: "Hạn Chót Tiếp Theo",
    noUpcomingDeadlines: "Không có hạn chót sắp tới",
    atStake: "Đang bị đặt cược:",
    quickAction: "Hành Động Nhanh",
    viewFullRoadmap: "Xem Lộ Trình Đầy Đủ",
    seeAllMicro: "Xem tất cả hạn chót vi mô →",
    overdue: "QUÁ HẠN",

    // Create Assignment
    createTitle: "Tạo Bài Tập Mới",
    createSubtitle: "Tự động tạo lộ trình hành vi bằng AI",
    subjectCourse: "Môn Học / Khóa Học",
    subjectPlaceholder: "vd: Kỹ Thuật Phần Mềm",
    finalDeadline: "Hạn Chót Cuối Cùng",
    datePickerPlaceholder: "Chọn ngày",
    assignmentDescription: "Mô Tả Bài Tập",
    descriptionPlaceholder: "vd: Bài nghiên cứu cuối kỳ về kiến trúc đám mây",
    difficultyLevel: "Mức Độ Khó",
    diffEasy: "dễ",
    diffMedium: "trung bình",
    diffHard: "khó",
    tasks: "nhiệm vụ",
    progressivePointSystem: "Hệ Thống Điểm Lũy Tiến",
    progressiveDesc: "Điểm tăng theo thời gian: nhiệm vụ đầu = ít rủi ro, nhiệm vụ cuối = áp lực tối đa",
    aiPowered: "Công Cụ Tạo Lộ Trình AI",
    aiDesc: "Hệ thống phân tích bài tập và tự động tạo các hạn chót vi mô theo thời gian với tiền gửi điểm dựa trên tâm lý học hành vi.",
    generateRoadmap: "Tạo Lộ Trình",
    generatingRoadmap: "Đang tạo lộ trình AI...",
    howItWorks: "📊 Cách Hoạt Động",
    step1: "AI chia bài tập thành các mốc tuần tự",
    step2: "Mỗi mốc được lên lịch hạn chót tự động",
    step3: "Điểm tăng dần (áp lực cao hơn = rủi ro cao hơn)",
    step4: "Hoàn thành để thu hồi điểm, bỏ lỡ = mất vĩnh viễn",
    lossAversion: "💡 Né Tránh Tổn Thất",
    lossAversionDesc: "Nghiên cứu cho thấy người ta có động lực gấp 2 lần để tránh mất mát hơn là đạt được lợi ích. Điểm gửi của bạn tạo ra cam kết thực sự.",

    // Roadmap View
    allRoadmaps: "Tất Cả Lộ Trình",
    allRoadmapsSubtitle: "Xem và quản lý tất cả dòng thời gian bài tập",
    deleteRoadmap: "Xóa lộ trình",
    deleteRoadmapTitle: "Xóa lộ trình này?",
    deleteRoadmapDesc: "Hành động này không thể hoàn tác. Lộ trình và toàn bộ dữ liệu sẽ bị xóa.",
    deleteRoadmapRefund: "Điểm hoàn lại (task chưa mất điểm):",
    deleteRoadmapLost: "Điểm mất vĩnh viễn (đã quá hạn):",
    deleteRoadmapNoRefund: "Không có điểm để hoàn lại.",
    deleteRoadmapConfirm: "Xóa lộ trình",
    deleting: "Đang xóa...",
    cancel: "Hủy",
    noAssignments: "Chưa có bài tập",
    createFirstAssignment: "Tạo Bài Tập Đầu Tiên",
    progress: "Tiến Độ",
    tasksDone: "Hoàn Thành",
    points: "Điểm",
    backToDashboard: "Về Bảng Điều Khiển",
    due: "Hạn",
    overallProgress: "Tiến Độ Tổng Thể",
    tasksComplete: "Nhiệm Vụ Hoàn Thành",
    remaining: "còn lại",
    totalValue: "Tổng Giá Trị",
    totalPoints2: "Tổng điểm",
    pointDistStrategy: "📊 Chiến Lược Phân Phối Điểm",
    pointDistDesc: "Chú ý cách giá trị điểm tăng khi hạn chót đến gần - tạo ra áp lực hành vi ngày càng cao!",
    pointsCurrentlyAtRisk: "Điểm Đang Rủi Ro",
    completeActiveAlert: "Hoàn thành các nhiệm vụ đang hoạt động trước hạn chót để thu hồi điểm. Bỏ lỡ hạn chót = mất vĩnh viễn!",
    assignmentTimeline: "Dòng Thời Gian Bài Tập",
    milestones: "Mốc Quan Trọng",
    assignmentNotFound: "Không tìm thấy bài tập",
    createNewAssignment: "Tạo Bài Tập Mới",

    // Task Detail
    taskComplete: "Hoàn Thành Nhiệm Vụ!",
    pointsReclaimedMsg: "Điểm đã được thu hồi!",
    back: "← Quay Lại",
    deadline: "Hạn Chót",
    pointsAtRiskLabel: "điểm đang rủi ro",
    completeTaskNote: "Hoàn thành nhiệm vụ này trước hạn chót để thu hồi tất cả",
    description: "Mô Tả",
    taskChecklist: "Danh Sách Kiểm Tra",
    done: "xong",
    warningPointLoss: "Cảnh Báo: Mất Điểm",
    warningDesc1: "Nếu bạn bỏ lỡ hạn chót này,",
    warningDesc2: "điểm sẽ bị mất vĩnh viễn và không thể phục hồi.",
    completeTaskBtn: "Hoàn Thành & Thu Hồi",
    pointsSuffix: "Điểm",

    // Deposit Points
    pointVault: "Kho Điểm",
    manageDeposits: "Quản lý tiền gửi hành vi",
    totalBalance: "Tổng Số Dư",
    availablePoints: "Điểm Khả Dụng",
    deposited: "Đã Gửi",
    reclaimed: "Đã Thu Hồi",
    lost: "Mất Vĩnh Viễn",
    addPoints: "Thêm Điểm",
    depositAmount: "Số Điểm Gửi",
    depositBtn: "Gửi",
    depositNote: "💡 Điểm gửi sẽ được phân bổ cho các vi nhiệm vụ của bài tập tiếp theo",
    recentActivity: "Hoạt Động Gần Đây",
    lossAversionPsych: "Tâm Lý Học Né Tránh Tổn Thất",
    lossAversionPsychDesc: "Nghiên cứu cho thấy người ta có động lực gấp 2 lần để tránh mất mát hơn là nhận phần thưởng. Điểm gửi tạo ra cam kết thực sự!",
    conversionRate: "100 ₫ = 1 điểm. Thanh toán qua SePay (QR chuyển khoản).",
    selectPackage: "Chọn gói nạp",
    payWithSePay: "Thanh toán",
    paymentProcessing: "Đang chuyển tới SePay...",
    paymentSuccess: "Thanh toán thành công!",
    paymentError: "Thanh toán thất bại",
    paymentErrorDesc: "Thanh toán bị hủy hoặc thất bại. Không có điểm nào được cộng.",
    paymentVerifying: "Đang xác minh thanh toán...",
    paymentPendingTitle: "Đang xử lý thanh toán",
    paymentPendingDesc: "Thanh toán đang được xác nhận. Điểm sẽ được cộng sau khi SePay gửi thông báo.",
    backToWallet: "Về Kho Điểm",
    sepayNotConfigured: "SePay chưa được cấu hình. Thêm SEPAY_MERCHANT_ID và SEPAY_SECRET_KEY vào .env",
    topupLabel: "Nạp qua SePay",
    noTransactions: "Chưa có giao dịch",
    loading: "Đang tải...",

    // Social
    socialTitle: "Tiến Độ Xã Hội",
    socialSubtitle: "Cạnh tranh với bạn bè",
    yourRank: "Xếp Hạng Của Bạn",
    of: "trong",
    dayStreak: "Chuỗi Ngày 🔥",
    completed: "Đã Hoàn Thành",
    shareProg: "Chia Sẻ Tiến Độ",
    leaderboard: "Bảng Xếp Hạng",
    friendActivity: "Hoạt Động Bạn Bè",
    views: "lượt xem",
    reactions: "phản ứng",
    peerPressure: "Áp Lực Đồng Nghiệp Có Tác Dụng!",
    peerPressureDesc: "Nghiên cứu cho thấy đối tác chịu trách nhiệm tăng tỷ lệ thành công lên 65%. Hãy cập nhật cho bạn bè!",

    // Risk Dashboard
    riskTitle: "Bảng Rủi Ro",
    riskSubtitle: "Theo dõi tổn thất và rủi ro sắp tới",
    totalLost: "Tổng Điểm Đã Mất",
    forever: "mãi mãi",
    currentAtRisk: "Đang Rủi Ro",
    missedDeadlinesStat: "Hạn Chót Bỏ Lỡ",
    avgLoss: "Mất Trung Bình / Lỡ",
    upcomingRisks: "Rủi Ro Sắp Tới",
    noUpcomingRisks: "Không có rủi ro sắp tới! 🎉",
    risk: "rủi ro",
    riskTrend: "Xu Hướng Rủi Ro",
    lossHistory: "Lịch Sử Mất Điểm",
    lossAversionAction: "Né Tránh Tổn Thất Trong Thực Tế",
    lossAversionActionDesc: "Mỗi điểm mất đi là mất mãi mãi. \"Vết đau\" cảm xúc này được thiết kế để thúc đẩy hoàn thành nhất quán các hạn chót vi mô.",
    lost2: "Đã mất:",
    riskLabel: "Rủi ro:",
    hoursLeft: "giờ còn",
    daysLeft: "ngày",

    // RoadmapTimeline
    timelineActive: "đang hoạt động",
    timelineUpcoming: "sắp tới",
    timelineLocked: "đã khóa",
    timelineCompleted: "đã hoàn thành",
    completeTaskTimeline: "Hoàn Thành",

    // PointDistributionPreview
    pointDistTitle: "Xem Trước Phân Phối Điểm",
    pointDistEarlyLabel: "Nhiệm Vụ Đầu",
    pointDistFinalLabel: "Nhiệm Vụ Cuối",
    pointDistNote: "Nhiệm vụ cuối mang",
    pointDistNote2: "điểm nhiều hơn nhiệm vụ đầu — áp lực tối đa khi cần thiết!",
    pointDistPsych: "📈 Thiết Kế Hành Vi: Rủi ro tăng dần để phản ánh áp lực hạn chót thực tế.",

    lectureUpload: "Tài Liệu Bài Giảng (PDF)",
    lectureUploadHint: "Nhấn để thêm PDF bài giảng (nhiều file)",
    lectureUploadSub: "Tải toàn bộ tài liệu môn học — không giới hạn số file. AI phân tích tất cả.",
    lectureFilesCount: "file",
    lectureRequired: "Vui lòng tải PDF bài giảng",
    insufficientBalance: "Không đủ điểm trong ví",
    timelineForfeited: "đã mất",
    uploadNotes: "Bước 1: Tải Ghi Chú Học Tập",
    uploadNotesDesc: "Tải ít nhất 1 file ghi chú kiến thức đã học",
    uploadNotesBtn: "Chọn file",
    noteRequired: "Hãy tải ít nhất một file ghi chú trước",
    quizTitle: "Bước 2: Bài Kiểm Tra (10 câu)",
    quizDesc: "Trả lời đúng ít nhất 7/10 câu để hoàn thành mốc",
    startQuiz: "Tạo & Bắt Đầu Quiz",
    generatingQuiz: "Đang tạo quiz bằng AI...",
    answerAllQuestions: "Vui lòng trả lời đủ 10 câu",
    depositOnCreate: "Điểm được cọc khi tạo bài tập mới",
    uploading: "Đang tải lên...",
    regenerateQuiz: "Tạo lại quiz",
    quizHistory: "Lịch Sử Quiz",
    answersSaved: "Đáp án",
  },
};

type TranslationKey = keyof typeof translations.en;
type Translations = typeof translations.en;

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: Translations;
}

const LanguageContext = createContext<LanguageContextType | null>(null);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>("vi");

  const t = translations[language];

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used inside LanguageProvider");
  return ctx;
}
